- name: installation du jdk8
  package: name=openjdk-8-jdk-headless state=present

- name: creation de l'utilisateur wildfly
  user:
    name: wildfly
    system: yes

- name: telechargement et desarchivage de wildfly
  unarchive:
    src: '{{wildfly_url}}'
    dest: /opt/
    owner: wildfly
    remote_src : yes
    creates: '{{wildfly_path}}'
    
- name: copie de wildfly dans /opt/wildfly
  command: mv '{{wildfly_path}}' '{{wildfly_opt}}'
     
- name: creation de /etc/wildfly + droits utilisateur
  file:
    path: '{{wildfly_etc}}'
    state: directory
    owner: wildfly
    group: wildfly
    mode: 0755

- name: copie du fichier conf vers /opt/wildfly + droits utilisateur
  copy:
    src: '{{wildfly_conf}}'
    dest: '{{wildfly_etc}}'
    owner: wildfly
    group: wildfly
    mode: 0755
    remote_src: yes

- name: copie du fichier service vers /etc/systemd/system
  copy:
    src: '{{wildfly_service}}'
    dest: '/etc/systemd/system/'
    remote_src: yes

- name: creation de /opt/wildfly/bin + droits utilisateur
  file:
    path: '{{wildfly_opt}}/bin'
    state: directory
    owner: wildfly
    group: wildfly
    mode: 0755

- name: copie du fichier launch vers /opt/wildfly/bin + droits utilisateur
  copy:
    src: '{{wildfly_launch}}'
    dest: '/opt/wildfly/bin'
    owner: wildfly
    group: wildfly
    mode: 0755
    remote_src: yes

- name: lancement du service wildfly
  systemd:
    state: restarted
    daemon_reload: yes
    name: wildfly
    enabled: yes
